org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.21.4

# https://maven.architectury.dev/architectury-plugin/architectury-plugin.gradle.plugin
architectury_plugin_version=3.4-SNAPSHOT
# https://maven.architectury.dev/dev/architectury/loom/dev.architectury.loom.gradle.plugin
architectury_loom_version=1.9-SNAPSHOT
enabled_platforms=fabric,forge

archives_base_name=Amoji
mod_version=1.0.4
maven_group=red.bread

# https://fabricmc.net/develop/
fabric_loader_version=0.16.10
fabric_api_version=0.114.1+1.21.4

# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=1.21.4-54.0.16
